ALTER TABLE "ideas" ALTER COLUMN "idea_id" DROP DEFAULT;--> statement-breakpoint
DROP SEQUENCE "ideas_idea_id_seq";--> statement-breakpoint
ALTER TABLE "ideas" ALTER COLUMN "idea_id" SET DATA TYPE integer USING "idea_id"::integer;--> statement-breakpoint
ALTER TABLE "ideas" ALTER COLUMN "idea_id" ADD GENERATED BY DEFAULT AS IDENTITY (sequence name "ideas_idea_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1);--> statement-breakpoint
SELECT setval('ideas_idea_id_seq'::regclass, (SELECT COALESCE(MAX(id), 1) FROM "ideas"), false);